### ISSUE TITLE
Cannot write to vesc 

### ISSUE THREAD

**Issue by buddasticks** [KeiranHines/VescThrottleController#4]
Works great except that vesc tool can only read data not write to the vesc 

Eg cannot change profile 
Eg cannot change motor current

**Comment by KeiranHines** [comment]
Hi @buddasticks can you provide details of the vesc and app version you are using?
In testing I have been able to fully control the Flipsky  Vesc in UART  mode from my esp d1 mini clone.

**Comment by buddasticks** [comment]
Hello Keiran

I am using flipsky 75100
Firmware 5.03
And android app version 3.01

**Comment by KeiranHines** [comment]
Can you please confirm your wiring, baud rate and pinout. The esp should be wired into the comm header

Additionally are you able to activate the motor using the bottom throttle at all, or is this untested?

**Comment by buddasticks** [comment]
Sorry I didn't mention I am just using it as ble serial passthrough .. the throttle is run via adc to the vesc 
Baud rate in app is 115200 bos
Tx2rx2 both wired to the com port .. live data works eg speedo and amp draw

**Comment by buddasticks** [comment]
![Uploading Screenshot_2022-03-29-21-34-33-82_ac858969194161e79cd74233a4908dd2.jpg…]()

**Comment by buddasticks** [comment]
Same times this error shows up

**Comment by KeiranHines** [comment]
Hi @buddasticks  Please see the attached PR. Please let me know if you have any further issues, if you do not have any issues I would appreciate an approval on the PR. 

If no review or further feedback is given within 7 days I will consider this PR closed and the PR able to be merged. 

I thank you for finding and reporting this issue.

**Comment by buddasticks** [comment]
please merge .. it has fixed my writing issues
